### ISSUE TITLE
No Webserver included

### ISSUE THREAD

**Issue by ApolloDS** [exira/docker-nsedit#1]
Hi,
I tried your image but there's missing a web server with php in the base image.

How should I start the nsedit?

**Comment by CumpsD** [comment]
We use separate images each dedicated to a single task, in this case php-fpm and nginx:
- https://github.com/exira/docker-php-fpm
- https://github.com/exira/docker-nginx

Our `docker-compose.yml` looks like:

```
nsedit-php:
  environment:
    WEBSERVER_API_PASSWORD: *redacted*
    WEBSERVER_API_IP: *redacted*
    WEBSERVER_API_PORT: *redacted*
    PDNS_NS1: *redacted*
    PDNS_NS2: *redacted*
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: role=dns-master
  tty: true
  image: exira/php-fpm:7.0.4-1
  volumes_from:
  - nsedit-data
  stdin_open: true

nsedit-data:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: role=dns-master
  tty: true
  image: exira/nsedit:latest
  volumes:
  - /var/www
  stdin_open: true

nsedit:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.sidekicks: nsedit-php,nsedit-data
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: role=dns-master
  tty: true
  image: exira/nginx:1.9.12-1
  volumes:
  - /var/www/nsedit.conf:/etc/nginx/conf.d/default.conf:ro
  volumes_from:
  - nsedit-data
  stdin_open: true
```
